# Generated by Django 2.2.5 on 2020-05-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
